### ISSUE TITLE
Cuda Driver error inside Docker.

### ISSUE THREAD

**Issue by brolinA** [leggedrobotics/wild_visual_navigation#306]
Hi I am trying to run the repository in docker running on Ubuntu 20.04

The docker setup was successful and I was able to run the Jackle robot as expected. Then I tried to run wild_visual_navigation_ros inside the docker and I get the following error.

Command used
`roslaunch wild_visual_navigation_ros wild_visual_navigation.launch`

Error
![cuda_error](https://github.com/leggedrobotics/wild_visual_navigation/assets/48987734/559bc8df-89b4-4f45-b43a-17fdbc70fbfa)

This is the native cuda driver on my Ubuntu 20.04

![image](https://github.com/leggedrobotics/wild_visual_navigation/assets/48987734/5ed06035-10a7-4c07-bf8e-cd7293721502)

Should the cuda version match between the docker image and my native system? Or is there something else that is causing the error.

**Comment by mmattamala** [comment]
Hi @brolinA thanks for reporting this.
Can you check if you can:
- do `nvidia-smi` **inside the container**?
- do `python3 -c "import torch; print(torch.cuda.is_available())"` **inside the container**

I share your concern that there could be some incompatibility or driver issue.

**Comment by brolinA** [comment]
Hi @mmattamala,
Thank you for the response. Unfortunately, I am not able to enter docker after restarting my system. I keep getting the following error.

```
[+] Running 0/0
 ⠋ Container docker-wvn_nvidia-1  Recreate                                                                                                                                                                    0.0s 
Error response from daemon: unknown or invalid runtime name: nvidia
```

I have made sure that both `nvidia-docker2` and `nvidia-container-toolkit` has been installed. Still it doesn't work. It was working the last time but doesn't work after restarting the PC. 

Any idea how to tackle this issue.

**Comment by mmattamala** [comment]
I think that something is messed up with the nvidia docker configuration. Can you check that all the steps are correct? https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-docker

Similarly, this thread might have some tips: https://stackoverflow.com/questions/52865988/nvidia-docker-unknown-runtime-specified-nvidia

**Comment by brolinA** [comment]
Hi @mmattamala,
Thank you. I was able to fix it. 

Here is the output of the commands you mentioned.

![image](https://github.com/leggedrobotics/wild_visual_navigation/assets/48987734/0255afb7-ddcf-4b17-a065-fcfc1e98ef55)

**Comment by mmattamala** [comment]
Good to know it helped.

Coming back to the original issue, it seems to be some mismatch between the driver in the host system and the container (because the nvidia-smi output doesn't match)

I'm a bit short on time at the moment to take a deeper look, but I recommend to search for similar issues with docker.

**Comment by andreschreiber** [comment]
Adding on to this -- I had the exact same issue (same error messages).
Using nvidia-smi in the container showed CUDA 12.3 whereas outside of the container it showed CUDA 12.2.
Changing the Dockerfile to use:
`FROM nvidia/cuda:12.2.2-runtime-ubuntu20.04 as base`
fixed the issue for me.

**Comment by mmattamala** [comment]
Thanks @andreschreiber for the proposed fix! I'll close the issue

**Comment by fwx20020105** [comment]
> Hi I am trying to run the repository in docker running on Ubuntu 20.04你好，我正在尝试用运行在 Ubuntu 20.04 上的 docker 中运行这个仓库
> 
> The docker setup was successful and I was able to run the Jackle robot as expected. Then I tried to run wild_visual_navigation_ros inside the docker and I get the following error.docker 设置成功了，我能够如预期运行 Jackle 机器人。然后我尝试在 docker 里运行 wild_visual_navigation_ros，结果出现了以下错误。
> 
> Command used  使用的指令 `roslaunch wild_visual_navigation_ros wild_visual_navigation.launch`
> 
> Error  错误 ![cuda_error](https://github.com/leggedrobotics/wild_visual_navigation/assets/48987734/559bc8df-89b4-4f45-b43a-17fdbc70fbfa)
> 
> This is the native cuda driver on my Ubuntu 20.04这是我 Ubuntu 20.04 上的原生 Cuda 驱动
> 
> ![image](https://github.com/leggedrobotics/wild_visual_navigation/assets/48987734/5ed06035-10a7-4c07-bf8e-cd7293721502)
> 
> Should the cuda version match between the docker image and my native system? Or is there something else that is causing the error.Cuda 版本应该和我的原生系统匹配吗？还是说有其他原因导致了错误？

I'm sorry to bother you.I found that the Google Drive links for checkpoints and rosbags are returning 404 errors. I was wondering if you still have the relevant field rosbag files available. If so, could you please send them to my email address: 1035664828@qq.com? I would be extremely grateful.
